[build]
  publish = "/public"

[[edge_functions]]
  path = "/contact"
  function = "email"

[[headers]]
  for = "/public/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, s-maxage=31536000"

[[redirects]]
  from = "/*"
  to = "/"
  status = 200
